// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"github.com/rendyuwu/gin-shortner-api/app"
	"github.com/rendyuwu/gin-shortner-api/controller"
	"github.com/rendyuwu/gin-shortner-api/env"
	"github.com/rendyuwu/gin-shortner-api/repository"
	"github.com/rendyuwu/gin-shortner-api/router"
	"github.com/rendyuwu/gin-shortner-api/service"
)

// Injectors from injector.go:

func InitializedServer() *gin.Engine {
	myEnv := env.NewEnv()
	db := app.NewDB(myEnv)
	shortenerRepository := repository.NewShortenerRepository(db)
	shortenerService := service.NewShortenerService(shortenerRepository)
	shortenerController := controller.NewShortenerController(shortenerService)
	engine := router.NewRouter(shortenerController)
	return engine
}

// injector.go:

var shortenerSet = wire.NewSet(repository.NewShortenerRepository, service.NewShortenerService, controller.NewShortenerController)
